site_name: MCP-Secure-Suite
site_url: https://rishitnanda.github.io/mcp_secure/
repo_url: https://github.com/rishitnanda/mcp_secure
theme:
  name: material
  font:
    text: Roboto
    code: Fira Code
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top

nav:
  - Home: index.md
  - Configuration: configuration.md
  - Security: security_layers.md
  - Benchmarks: benchmark.md
  - Architecture: architecture.md
  - Limitations: limitations.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
